validator: increase timeout for reconnect::reconnect_doesnt_break_fullscan
During tests with debug scylla version it seems that 10s wait for index build
is too little. Needs to increase to 20s.

```
INFO  2025-10-31 01:26:55,057 [shard 0:main] init - Scylla version 2026.1.0~dev-0.20251030.fc7b8602d92c initialization completed.
2025-10-30T23:26:55.273311Z  WARN unable to get latest schema change from db: Failed to fetch the first page of the result: No connections in the pool: The pool is broken; Last connection failed with: Connection refused (os error 111)
2025-10-30T23:26:55.294569Z  WARN Lost connection during scan of the range (Token { value: -9186960056414191408 }, Token { value: -9111254506410003749 }), retrying
2025-10-30T23:26:55.435949Z ERROR response failed classification=Status code: 503 Service Unavailable latency=0 ms
ERROR 2025-10-31 01:26:55,436 [shard 0:sl:d] vector_store_client - Vector Store returned error: HTTP status 503 Service Unavailable: Index ks_70c5aa9e85ab4be9a1419f1bf6508062.idx_1f9de708614a468caebccc632995a648 is not available yet as it is still being constructed, progress: 0.197%
2025-10-30T23:26:55.543506Z ERROR response failed classification=Status code: 503 Service Unavailable latency=0 ms

[start wait for index build at 23:26::55 with progress 0.197%]

ERROR 2025-10-31 01:27:01,709 [shard 1:sl:d] vector_store_client - Vector Store returned error: HTTP status 503 Service Unavailable: Index ks_70c5aa9e85ab4be9a1419f1bf6508062.idx_1f9de708614a468caebccc632995a648 is not available yet as it is still being constructed, progress: 0.197%
2025-10-30T23:27:01.812728Z ERROR response failed classification=Status code: 503 Service Unavailable latency=0 ms
ERROR 2025-10-31 01:27:01,813 [shard 0:sl:d] vector_store_client - Vector Store returned error: HTTP status 503 Service Unavailable: Index ks_70c5aa9e85ab4be9a1419f1bf6508062.idx_1f9de708614a468caebccc632995a648 is not available yet as it is still being constructed, progress: 1.743%
2025-10-30T23:27:01.917514Z ERROR response failed classification=Status code: 503 Service Unavailable latency=0 ms

[at 23:27:02 (after 4:07s) restarting full scan with progress 1.743%]

ERROR 2025-10-31 01:27:05,276 [shard 1:sl:d] vector_store_client - Vector Store returned error: HTTP status 503 Service Unavailable: Index ks_70c5aa9e85ab4be9a1419f1bf6508062.idx_1f9de708614a468caebccc632995a648 is not available yet as it is still being constructed, progress: 84.532%
2025-10-30T23:27:05.328826Z ERROR test-case{name="reconnect"}:test{name="reconnect_doesnt_break_fullscan"}: panicked at /jenkins/.cargo/git/checkouts/vector-store-184327367faff5fe/4c0db24/crates/validator-tests/src/common.rs:97:25:
Timeout on: Waiting for index build

[at 23:27:05 (after 10s) full scan with progress 84.532%]

```